[versions]

[libraries]

flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }
postgresql = { module = "org.postgresql:postgresql" }
spring-boot-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
spring-boot-webmvc-test = { module = "org.springframework.boot:spring-boot-webmvc-test" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }

[plugins]

[bundles]
spring-security = ["spring-boot-oauth2-resource-server"]