[versions]
siloverse-messaging = "1.0.11-SNAPSHOT"
opentelemetry-logback-appender = "2.28.0-alpha"

[libraries]
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }
postgresql = { module = "org.postgresql:postgresql" }

siloverse-messaging-core = { module = "io.github.siloverse:messaging-core", version.ref = "siloverse-messaging" }
siloverse-messaging-rabbitmq = { module = "io.github.siloverse:messaging-rabbitmq", version.ref = "siloverse-messaging" }
siloverse-messaging-spring = { module = "io.github.siloverse:messaging-spring", version.ref = "siloverse-messaging" }

spring-boot-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
spring-boot-webmvc-test = { module = "org.springframework.boot:spring-boot-webmvc-test" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }

jackson-databind = { module = "tools.jackson.core:jackson-databind" }
jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin" }

micrometer-tracing-bridge-otel = { module = "io.micrometer:micrometer-tracing-bridge-otel" }
opentelemetry-exporter-otlp = { module = "io.opentelemetry:opentelemetry-exporter-otlp" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus" }
opentelemetry-logback-appender = { module = "io.opentelemetry.instrumentation:opentelemetry-logback-appender-1.0", version.ref = "opentelemetry-logback-appender" }
spring-boot-starter-opentelemetry = { module = "org.springframework.boot:spring-boot-starter-opentelemetry" }

[plugins]

[bundles]
jackson = ["jackson-databind", "jackson-module-kotlin"]
siloverse-messaging = [
    "siloverse-messaging-core",
    "siloverse-messaging-rabbitmq",
    "siloverse-messaging-spring"
]
spring-security = ["spring-boot-oauth2-resource-server"]

siloverse-observability = [
    "micrometer-registry-prometheus",
    "opentelemetry-exporter-otlp",
    "micrometer-tracing-bridge-otel",
    "spring-boot-starter-opentelemetry",
    "opentelemetry-logback-appender"
]