server:
  port: 10101
spring:
  application:
    name: user-silo
  datasource:
    url: jdbc:postgresql://postgres.macgrant-platform.test:5432/siloverse
    username: user-silo
    password: ${USER_SILO_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    default-schema: user_silo
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.macgrant-platform.test/realms/kyc
logging:
  level:
    org.springframework.security: TRACE
