server:
  port: 10101
spring:
  application:
    name: user-silo
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.macgrant-platform.test/realms/kyc
logging:
  level:
    org.springframework.security: TRACE
